//
//  MainView.h
//  FFC
//
//  Created by Shankar on 6/3/09.
//  Copyright 2010 TapFantasy. All rights reserved.
//

#import <GameKit/GameKit.h>
#import <StoreKit/StoreKit.h>
#import <StoreKit/SKPaymentTransaction.h>
#import <AVFoundation/AVFoundation.h>
#import "DialogBoxView.h"
#import "WelcomeViewController.h"
#import <FacebookSDK/FacebookSDK.h>

@class AboutView;
@class ChallengeView;
@class ChallengeCreateView;
@class Header;
@class JobsView;
@class ClubView;
@class StadiumView;
@class UpgradeView;
@class StadiumMap;
@class FansView;
@class FinanceView;
@class StaffView;
@class MatchView;
@class ClubSearchView;
@class FriendsView;
@class ClubMapView;
@class SquadView;
@class TrainingView;
@class NewsView;
@class MatchLive;
@class HelpView;
@class MatchReport;
@class ChatView;
@class GameController;
@class AchievementsView;
@class AllianceView;
@class AllianceDetail;
@class Footer;
@class Menu0;
@class MainCell;
@class SPViewController;

@interface MainView : UIViewController 
<DialogBoxDelegate, SKProductsRequestDelegate, SKPaymentTransactionObserver, 
UITabBarControllerDelegate, UIAlertViewDelegate, CLLocationManagerDelegate, 
AVAudioPlayerDelegate, UITableViewDataSource, UITableViewDelegate, FBFriendPickerDelegate>
{
	AVAudioPlayer *buttonAudio;
	AVAudioPlayer *backAudio;
    AVAudioPlayer *moneyAudio;
    AVAudioPlayer *winAudio;
    AVAudioPlayer *loseAudio;
	UIButton *imageButton;
	UIButton *backButton;
    GKSession *gameSession;
	UIView *activeView;
	UIView *previousView;
	UIView *superView;
	Header *header;
	JobsView *jobsView;
	ClubView *clubView;
	StadiumView *stadiumView;
    UpgradeView *upgradeView;
    StadiumMap *stadiumMap;
	FansView *fansView;
	FinanceView *financeView;
	StaffView *staffView;
	MatchView *matchView;
	ClubSearchView *clubSearchView;
	ClubMapView *clubMapView;
	SquadView *squadView;
	TrainingView *trainingView;
	NewsView *newsView;
	FriendsView *friendsView;
	MatchLive *matchLive;
	HelpView *helpView;
	MatchReport *matchReport;
	DialogBoxView *dialogBox;
	WelcomeViewController *welcomeView;
	AboutView *aboutBox;
	ChallengeView *challengeBox;
    ChallengeCreateView *challengeCreate;
    ChatView *chatView;
    SPViewController *sparrowView;
    AchievementsView *achievementsView;
    AllianceView *allianceView;
    AllianceDetail *allianceDetail;
    Footer *footerView;
    Menu0 *menu0;
	UITabBarController *storeTabBarController;
	UITabBarController *tacticsTabBarController;
	UITabBarController *cupTabBarController;
	UITabBarController *leagueTabBarController;
	UITabBarController *clubTabBarController;
	UITabBarController *myclubTabBarController;
    BOOL showedFooter;
	BOOL showedChallenge;
	UITextField *tf;
	CGFloat posxView;
	NSTimer *animateViewTimer;
	NSTimer *marqueeTimer;
    NSTimer *chatTimer;
    UILabel* lblChat1;
    UILabel* lblChat2;
	NSMutableArray *marquee;
	UILabel *lblMarquee;
	CGFloat posxMarquee;
	NSInteger rowMarquee;
    NSInteger speedMarquee;
	CGSize textSizeMarquee;
	UIAlertView *alertLoading;
    UIButton *loginButton;
    UITableView *mainTableView;
    MainCell *cell;
    NSInteger currMatchIndex;
}
@property (nonatomic, strong) IBOutlet UITableView *mainTableView;
@property (nonatomic, strong) AVAudioPlayer *buttonAudio;
@property (nonatomic, strong) AVAudioPlayer *backAudio;
@property (nonatomic, strong) AVAudioPlayer *moneyAudio;
@property (nonatomic, strong) AVAudioPlayer *winAudio;
@property (nonatomic, strong) AVAudioPlayer *loseAudio;
@property (nonatomic, strong) UIAlertView *alertLoading;
@property (nonatomic, strong) GKSession	 *gameSession;
@property (nonatomic, strong) UIView *activeView;
@property (nonatomic, strong) UIView *previousView;
@property (nonatomic, strong) UIView *superView;
@property (nonatomic, strong) Header *header;
@property (nonatomic, strong) JobsView *jobsView;
@property (nonatomic, strong) ClubView *clubView;
@property (nonatomic, strong) StadiumView *stadiumView;
@property (nonatomic, strong) UpgradeView *upgradeView;
@property (nonatomic, strong) StadiumMap *stadiumMap;
@property (nonatomic, strong) FansView *fansView;
@property (nonatomic, strong) FinanceView *financeView;
@property (nonatomic, strong) StaffView *staffView;
@property (nonatomic, strong) MatchView *matchView;
@property (nonatomic, strong) ClubSearchView *clubSearchView;
@property (nonatomic, strong) ClubMapView *clubMapView;
@property (nonatomic, strong) SquadView *squadView;
@property (nonatomic, strong) TrainingView *trainingView;
@property (nonatomic, strong) NewsView *newsView;
@property (nonatomic, strong) FriendsView *friendsView;
@property (nonatomic, strong) MatchLive *matchLive;
@property (nonatomic, strong) HelpView *helpView;
@property (nonatomic, strong) MatchReport *matchReport;
@property (nonatomic, strong) DialogBoxView *dialogBox;
@property (nonatomic, strong) WelcomeViewController *welcomeView;
@property (nonatomic, strong) AboutView *aboutBox;
@property (nonatomic, strong) ChallengeView *challengeBox;
@property (nonatomic, strong) ChallengeCreateView *challengeCreate;
@property (nonatomic, strong) ChatView *chatView;
@property (nonatomic, strong) AchievementsView *achievementsView;
@property (nonatomic, strong) AllianceView *allianceView;
@property (nonatomic, strong) AllianceDetail *allianceDetail;
@property (nonatomic, strong) Footer *footerView;
@property (nonatomic, strong) NSTimer *animateViewTimer;
@property (nonatomic, strong) NSTimer *marqueeTimer;
@property (nonatomic, strong) NSTimer *chatTimer;
@property (nonatomic, strong) NSMutableArray *marquee;
@property (nonatomic, strong) UILabel* lblMarquee;
@property (nonatomic, strong) UILabel* lblChat1;
@property (nonatomic, strong) UILabel* lblChat2;
@property (nonatomic, strong) UIButton *backButton;
@property (nonatomic, strong) Menu0 *menu0;
@property (nonatomic, strong) MainCell *cell;
@property (nonatomic, strong) SPViewController *sparrowView;
@property (nonatomic, strong) IBOutlet UITabBarController *storeTabBarController;
@property (nonatomic, strong) IBOutlet UITabBarController *tacticsTabBarController;
@property (nonatomic, strong) IBOutlet UITabBarController *cupTabBarController;
@property (nonatomic, strong) IBOutlet UITabBarController *leagueTabBarController;
@property (nonatomic, strong) IBOutlet UITabBarController *clubTabBarController;
@property (nonatomic, strong) IBOutlet UITabBarController *myclubTabBarController;
- (void)showAlert:(NSString*)title subtitle:(NSString*)subtitle message:(NSString*)message;
- (void)handleDidReceiveRemoteNotification:(NSDictionary *)userInfo;
- (void)paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions;
- (void)failedTransaction:(SKPaymentTransaction *)transaction;
- (void)restoreTransaction:(SKPaymentTransaction *)transaction;
- (void)completeTransaction:(SKPaymentTransaction *)transaction;
- (void)doTransaction:(SKPaymentTransaction *)transaction;
- (void)buyStadiumSuccess:(NSString *)virtualMoney :(NSString *)json;
- (void)buyStaffSuccess:(NSString *)virtualMoney :(NSString *)json;
- (void)buyOthersSuccess;
- (void)renameClubPurchaseSuccess:(NSString *)virtualMoney :(NSString *)json;
- (void)buyCoachSuccess;
- (void)startLiveMatch;
- (void)showHelp;
- (void)showChat;
- (void)updateHeader;
- (void)hideHeader;
- (void)hideFooter;
- (void)showHeader;
- (void)showFooter;
- (void)showMarquee;
- (void)hideMarquee;
- (void)slideView:(UIView *)coming go:(UIView *)going;
- (void)switchView:(UIView *)coming go:(UIView *)going dir:(NSUInteger)direction;
- (void)switchJobsView:(NSUInteger)direction;
- (void)updateTacticsView;
- (void)jumpToPlayerStore;
- (void)jumpToCoachStore;
- (void)jumpToOthersStore;
- (void)jumpToChallenge:(NSString *)club_id;
- (void)jumpToClubViewer:(NSString *)club_id;
- (void)jumpToFBClubViewer:(NSString *)fb_id;
- (void)removeClubViewer;
- (void)resetClubImages;
- (void)showWaitingBox;
- (void)createBackButton;
- (void)jumpToFinance;
- (void)jumpToFans;
- (void)jumpToTrain;
- (void)jumpToNews;
- (void)jumpToClub;
- (void)buyProduct:(NSString *)product;
- (void)buyResetClub;
- (void)liveMatch;
- (void)showWelcome;
- (void)removeWelcome;
- (void)showAchievements;
- (void)removeAchievements;
- (void)buttonSound;
- (void)trainingSound;
- (void)stopTrainingSound;
- (void)initSound;
- (void)backSound;
- (void)moneySound;
- (void)winSound;
- (void)loseSound;
- (void)showLogin;
- (void)addFunds;
- (void)reportMatch;
- (void)removeLiveMatch;
- (void)removeStore;
- (void)showStadiumUpgrade;
- (void)showBuildingUpgrade:(int)type;
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer *)player successfully:(BOOL)flag;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer *)player error:(NSError *)error;
- (void)fblogin;
- (void)addDiamonds;
- (void)menuButton_tap:(int)sender;
- (void)DeclineChallenge;
- (void)DeclineChallengeServer;
- (void)updateChallenge;
- (void)saveLocation;
- (void)logoutButton;
- (void)shareButton;
- (void)reloadViewFull;
- (void)FallbackPublishStory:(NSString *)message :(NSString *)caption :(NSString *)picture;
- (void)showFooterMessage;
- (void)reloadClub;
- (void)refillEnergySuccess:(NSString *)virtualMoney :(NSString *)json;
- (void)showLoadingAlert;
- (void)removeLoadingAlert;
- (void)reloadClubFromOutside;
- (void)createDialogBox;
- (void)removeDialogBox;
- (void)updateAchievementBadges;
- (void)showAlliance;
- (void)showAllianceDetail:(int)aid;
- (void)buyOthersSuccessWithDiamonds;
- (void)checkAccepted;
@end
